### ISSUE TITLE
Reformat code

### ISSUE THREAD

**Issue by shramko82** [Hopo4ka/NadiiaSkrupska.github.io#21]
Опять забываешь про форматирование кода.
Пожалуйста, на всех задачах 6+ урока сделай:

```
Ctrl+a
Ctrl+Alt+l
```

**Comment by NadiiaSkrupska** [comment]
та я делаю как нам на лекциях показывают :) обещаю исправиться, может не сразу, но буду идти к этому :))

**Comment by NadiiaSkrupska** [comment]
та я делаю как нам на лекциях показывают :) обещаю исправиться, может не сразу, но буду идти к этому :))
