### ISSUE TITLE
Lesson 3 task 4

### ISSUE THREAD

**Issue by shramko82** [Hopo4ka/NadiiaSkrupska.github.io#8]
It doesnt ready

**Comment by NadiiaSkrupska** [comment]
As there have been made changes in the task, I've rewrote the code

**Comment by shramko82** [comment]
Output should be like this:
1 
2 
Fizz 
4 
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
...

**Comment by NadiiaSkrupska** [comment]
sorry, I've missunderstood the task
